services:
    user_device_notification:
        class: Ibtikar\TaniaModelBundle\Service\UserDeviceNotification
        arguments: ["@doctrine.orm.entity_manager", "@firebase_cloud_messaging"]

    notification_center:
        class: Ibtikar\TaniaModelBundle\Service\NotificationCenter
        arguments: ["@doctrine.orm.entity_manager", "@user_device_notification"]

    validator.unique_city_item_price:
            class: Ibtikar\TaniaModelBundle\Validator\Constraints\UniqueCityItemPriceValidator
            arguments: ["@request_stack", "@translator"]
            tags:
                - { name: validator.constraint_validator, alias: uniqueCityItemPrice }

    validator.unique_phone:
            class: Ibtikar\TaniaModelBundle\Validator\Constraints\UniquePhoneValidator
            arguments: ["@translator", "@doctrine.orm.entity_manager"]
            tags:
                - { name: validator.constraint_validator, alias: uniquePhone }