services:
#    ibtikar_tania_model.example:
#        class: Ibtikar\TaniaModelBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api_operations:
        class: Ibtikar\TaniaModelBundle\Service\APIOperations
        arguments: [ '@validator', '@translator' ]
