<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * CityAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
