<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * CityAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityAreaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get city order created at rang from and to date
     * mainly created for the tania's integration
     * Abdelrahman.allam
     * @param datetime $fromDate
     * @param datetime $toDate
     * @return Orders list
     */
    public function getCityAreaUpdatedAt($fromDate, $toDate){
        $query = $this->createQueryBuilder('o');

        $query = $query->andWhere("o INSTANCE OF Ibtikar\TaniaModelBundle\Entity\CityArea")
                ->andWhere('o.updatedAt >= :start')
                ->andWhere('o.updatedAt <= :end')
                ->setParameters(['start' => $fromDate->format('Y-m-d H:i:s'),'end' => $toDate->format('Y-m-d H:i:s')])
                ->orderBy('o.id', 'DESC')
                ->getQuery()
                ->getResult();

        return $query;
    }
}
