<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * CityAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get city order created at rang from and to date
     * mainly created for the tania's integration
     *
     * @param datetime $fromDate
     * @param datetime $toDate
     * @return Orders list
     */
    public function getContactUsCreatedAt($fromDate, $toDate){
        $query = $this->createQueryBuilder('o');

        $query = $query->andWhere("o INSTANCE OF Ibtikar\TaniaModelBundle\Entity\ContactUs")
                ->andWhere('o.createdAt >= :start')
                ->andWhere('o.createdAt <= :end')
                ->setParameters(['start' => $fromDate->format('Y-m-d H:i:s'),'end' => $toDate->format('Y-m-d H:i:s')])
                ->orderBy('o.id', 'DESC')
                ->getQuery()
                ->getResult();

        return $query;
    }
}
