<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * DeviceNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
