<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * ItemHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemHomeRepository extends \Doctrine\ORM\EntityRepository
{
     function truncate() {
        return $this->createQueryBuilder('ih')
                        ->delete()
                        ->getQuery()
                        ->getResult();
    }

    function reorder($fromPosition, $toPosition, $shiftAmount) {
        if ($fromPosition > $toPosition) {
            $fromTemp = $fromPosition;
            $fromPosition = $toPosition;
            $toPosition = $fromTemp;
        }
        $em = $this->getEntityManager();
        return $em->createQuery('UPDATE IbtikarTaniaModelBundle:ItemHome ih '
                                . 'set ih.position = ih.position + :shiftAmount '
                                . 'where ih.position >= :fromPosition and ih.position <= :toPosition')
                        ->setParameter(":fromPosition", $fromPosition)
                        ->setParameter(":toPosition", $toPosition)
                        ->setParameter(":shiftAmount", $shiftAmount)
                        ->getResult();
    }

}
