<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * OrderOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
