<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * PhoneVerificationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Karim Shendy <kareem.elshendy@ibtikar.net.sa>
 */
class PhoneVerificationCodeRepository extends \Doctrine\ORM\EntityRepository
{

}