<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * RatingTagRaingRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingTagRaingRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
