<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * RatingTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingTagRepository extends \Doctrine\ORM\EntityRepository
{
}
