<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * RatingRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRangeRepository extends \Doctrine\ORM\EntityRepository
{
    function getRatingTagJoinRatingRange(){
        $query = $this->createQueryBuilder('rr')
            ->select('rr,rtrr,rt')
            ->innerJoin('rr.ratingTagRatingRanges', 'rtrr')
            ->innerJoin('rtrr.ratingTag', 'rt')                
            ->getQuery();
        return $query->getResult($query::HYDRATE_ARRAY);
    }
}
