<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * RatingTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingTagRepository extends \Doctrine\ORM\EntityRepository
{
    function getRatingTagsByRatingValue($value){
        $query = $this->createQueryBuilder('t')
            ->select('t')
            ->innerJoin('t.ratingTagRatingRanges', 'rtrr')
            ->innerJoin('rtrr.ratingRange', 'rr')                
            ->andWhere(":value >= rr.start and :value <= rr.end")
            ->setParameter(":value", $value)
            ->getQuery();
        return $query->getResult($query::HYDRATE_OBJECT);
    }
}
