<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * RatingRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
