<?php

namespace Ibtikar\TaniaModelBundle\Repository;

/**
 * UserPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
